/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BScustomerLogin;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author wangcong
 */
public class OrderHistoryJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount customer;
    /**
     * Creates new form OrderHistoryJPanel
     */
    public OrderHistoryJPanel(JPanel container,UserAccount customer) {
        this.container = container;
        this.customer = customer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnBuyingOrder = new javax.swing.JButton();
        btnSellingOrder = new javax.swing.JButton();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBuyingOrder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBuyingOrder.setText("Buying Order");
        btnBuyingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyingOrderActionPerformed(evt);
            }
        });

        btnSellingOrder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSellingOrder.setText("Selling Order");
        btnSellingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellingOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSellingOrder)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(btnBack))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(btnBuyingOrder))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addGap(30, 30, 30)
                .addComponent(btnBuyingOrder)
                .addGap(44, 44, 44)
                .addComponent(btnSellingOrder)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBuyingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyingOrderActionPerformed
        OrderBookHistoryJPanel orderBookHistoryJPanel = new OrderBookHistoryJPanel(container,customer);
        container.add("OrderBookHistoryJPanel", orderBookHistoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnBuyingOrderActionPerformed

    private void btnSellingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellingOrderActionPerformed
        OrderSellingHistoryJPanel orderSellingHistoryJPanel = new OrderSellingHistoryJPanel(container,customer);
        container.add("OrderSellingHistoryJPanel", orderSellingHistoryJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnSellingOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuyingOrder;
    private javax.swing.JButton btnSellingOrder;
    // End of variables declaration//GEN-END:variables
}
