/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PT_ManageRole;

import Business.Enterprise.Enterprise;
import userinterface.PB_ManagerRole.*;
import Business.OrderSystem.OrderDirectory;
import Business.OrderSystem.OrderItem;
import Business.Organization.Organization;
import Business.Organization.PT_PrintingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Date;
import javax.swing.table.JTableHeader;
/**
 *
 * @author admin
 */
public class PTManage_workAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    private UserAccount user;
    private Organization ptmanorg;
    //private OrderDirectory orderDirectory;
    public PTManage_workAreaJPanel( JPanel container, UserAccount user) {
        initComponents();
        this.container=container;
        this.user=user;
        this.ptmanorg=new PT_PrintingOrganization();
        labelUser.setText(user.getUsername());
        labelRole.setText(user.getEmployee().getEnterprise().getEnterpriseName()+" "+user.getEmployee().getOrganization().getOrgtypename());
        JTableHeader head = tblQueue.getTableHeader(); // 创建表格标题对象
        head.setPreferredSize(new Dimension(head.getWidth(), 36));// 设置表头大小
        head.setFont(new Font("Times New Romans", Font.PLAIN, 36));// 设置表格字体
        JTableHeader head1 = tblOrderItem.getTableHeader(); // 创建表格标题对象
        head1.setPreferredSize(new Dimension(head1.getWidth(), 36));// 设置表头大小
        head1.setFont(new Font("Times New Romans", Font.PLAIN, 36));// 设置表格字体
        populate();
        
        
        for(Organization or:user.getEmployee().getEnterprise().getOrganizationDirectory().getOrganizationList()){
            if(or.getOrgtypename().equals("PT_PrintingOrganization") ){
                ptmanorg=or;
                for(UserAccount ua:or.getUserAccountDirectory().getUserAccountList())
                        comboPrintMan.addItem(ua.getUsername());
            }
        }
        
    }
    
    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:user.getEmployee().getOrganization().getWorkQueue().getWorkRequestList()){
            if(wr.getStatus().equals("Uncompleted")){
                Object[] row=new Object[6];
                row[0]=wr;
                if(wr.getSenderEnterprise()!=null){
                    row[1]=wr.getSenderEnterprise().getEnterpriseName();
                    row[2]=wr.getSenderEnterprise().getPhone();               
                }else{
                    row[1]=wr.getSenderUserAccount().getUsername();
                    row[2]=wr.getSenderUserAccount().getPhone();
                }           
                row[3]=wr.getStatus();
                row[4]=wr.getMessage();
                row[5]=wr.getResolveDate();
                dtm.addRow(row);
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderItem = new javax.swing.JTable();
        labelRole = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUnfinished = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboPrintMan = new javax.swing.JComboBox<>();
        btnCommit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcome! ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        labelUser.setText("labelUser");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, 20));

        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Sender", "phone", "Status", "Message", "ResolveDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQueue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 880, 160));

        btnDetails.setText("Detials");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        tblOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookName", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tblOrderItem);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 880, 240));

        labelRole.setText("jLabel2");
        add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 170, 20));

        jLabel2.setText("Work Area");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        btnUnfinished.setText("Unfinished");
        btnUnfinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnfinishedActionPerformed(evt);
            }
        });
        add(btnUnfinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel3.setText("Assign to a Print Man:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 290, 50));

        comboPrintMan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        comboPrintMan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPrintMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrintManActionPerformed(evt);
            }
        });
        add(comboPrintMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 270, 50));

        btnCommit.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int row=tblQueue.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a work reuqest", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(row, 1);
            DefaultTableModel dtm=(DefaultTableModel)tblOrderItem.getModel();
            dtm.setRowCount(0);
            for(OrderItem oi:wr.getOrder().getOrderItems()){
                Object[] r=new Object[2];
                r[0]=oi;
                r[1]=oi.getQuantity()+"";
              
                dtm.addRow(r);
            }
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnUnfinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnfinishedActionPerformed
        populate();
    }//GEN-LAST:event_btnUnfinishedActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)tblQueue.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:user.getEmployee().getOrganization().getWorkQueue().getWorkRequestList()){
            Object[] row=new Object[6];
            row[0]=wr;
            if(wr.getReceiverEnterprise()!=null){
                row[1]=wr.getReceiverEnterprise().getEnterpriseName();
                row[2]=wr.getReceiverEnterprise().getPhone();               
            }else{
                row[1]=wr.getReceiverUserAccount().getUsername();
                row[2]=wr.getReceiverUserAccount().getPhone();
            }           
            row[3]=wr.getStatus();
            row[4]=wr.getMessage();
            row[5]=wr.getResolveDate();
            dtm.addRow(row);
        }
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed

        
       int row=tblQueue.getSelectedRow();
       String selectedprintmanua=(String)comboPrintMan.getSelectedItem();
       // UserAccount selectedPrintMan=(UserAccount)comboPrintMan.getSelectedItem();
       UserAccount selectedPrintMan=new UserAccount();
       
        for(UserAccount us:ptmanorg.getUserAccountDirectory().getUserAccountList()){
            if(selectedprintmanua==us.getUsername()){
            selectedPrintMan=us;
            }
        
        }
        
        if(row<0||selectedPrintMan==null){
            if(row<0)
            JOptionPane.showMessageDialog(null, "Please select a work reuqest", "Warning", JOptionPane.WARNING_MESSAGE);
            else if(selectedPrintMan==null) 
            JOptionPane.showMessageDialog(null, "Please choose a pringting man", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }else{
            WorkRequest wr=(WorkRequest)tblQueue.getValueAt(row, 1);
            
            WorkRequest newReq=new WorkRequest();
            newReq.setOrder(wr.getOrder());
            newReq.setSenderUserAccount(user);
            newReq.setStatus("Uncompleted");
            newReq.setRequestDate(new Date());
            newReq.setReceiverUserAccount(selectedPrintMan);

             //message
            int check=JOptionPane.YES_NO_OPTION;
            String mesg = JOptionPane.showInputDialog(null,"Message: \n","Mesg",check);
            if(check==JOptionPane.YES_OPTION){
                newReq.setMessage(mesg);
                JOptionPane.showMessageDialog(null, "A new work request has been sent out successfully.");
                wr.setStatus("Completed");
                wr.setResolveDate(new Date());
                selectedPrintMan.getWorkQueue().addNewRequest(newReq);
                populate(); 
            }
                
        }
                    

    }//GEN-LAST:event_btnCommitActionPerformed

    private void comboPrintManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrintManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrintManActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnUnfinished;
    private javax.swing.JComboBox<String> comboPrintMan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTable tblOrderItem;
    private javax.swing.JTable tblQueue;
    // End of variables declaration//GEN-END:variables
}
